name: MyWarp
author: Albert
main: me.albert.mywarp.MyWarp
version: 1.0.1
api-version: 1.13
commands:
  mywarp:
    description: main command
  warp:
    aliases: [mwarp]
    description: warp to a warp
    permission: mywarp.warp
  setwarp:
    aliases: [msetwarp]
    permission: mywarp.setwarp
  warplist:
    permission: mywarp.list
    description: list own warps
  dewarp:
    aliases: [mdewarp]
    permission: mywarp.dewarp